_BASE_: "./Base-RCNN-FPN.yaml"
OUTPUT_DIR: "test"
MODEL:
  MASK_ON: False
  LOAD_PROPOSALS: False
  RESNETS:
    DEPTH: 50
DATASETS:
  TRAIN: ("crowdai_buildings_detection_train",)
  TEST: ("crowdai_buildings_detection_val",)
DATALOADER:
  NUM_WORKERS: 8
SOLVER:
  BASE_LR: 0.02